#######################################################
## i3 - Default application(s)											 ##
#######################################################

## Set default applications
set $browser "firefox"
set $incognito "firefox --private-window --"
set $terminal "wezterm"
set $editor "nvim"
set $runeditor "wezterm start nvim" 
set $runmp "wezterm start ncmpcpp"

## Custom scripts folder
set $sk $HOME/.config/i3/sk
